[manifest]
version = '1.0.1'
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'before'
pattern = '''
local cols
'''
payload = '''
if obj and obj.config.taw_data and obj.config.taw_data.art_credit then
    badges[#badges + 1] = create_badge(localize('taw_credit', "labels")..obj.config.taw_data.art_credit, G.C.CLEAR, SMODS.get_badge_text_colour(G.C.GREY), 0.9)
end

'''